version: '3'

services:
  is-academia-bot:
    image: canardconfit/is-academia-bot:latest
    container_name: is-academia-bot
    restart: always
    volumes:
      - "./git-history:/app/git-history"
    env_file:
      - "./environment.env"