version: '3'

services:
  is-academia-bot:
    image: ghcr.io/canardconfit/is-academia-bot:latest
    container_name: is-academia-bot
    restart: always
    env_file:
      - "D:/Users/Tom/Desktop/.env"